name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
		
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: npm

      - name: Build
        run: |
          npm ci
          # configure the build here

      - name: Deploy
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll